# Generated by Django 4.2.6 on 2024-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_articulos_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen_Producto',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/%Y%m/', verbose_name='Imagen Producto'),
        ),
    ]
