# Generated by Django 4.2.6 on 2024-03-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_eventos_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='foto',
            new_name='imagen_Evento',
        ),
    ]
