# Generated by Django 4.2.6 on 2024-03-04 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0009_alter_inventario_cantidad_totalventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_bodega',
            name='id_Usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario'),
        ),
        migrations.AddField(
            model_name='pedido_mesero',
            name='id_Usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario'),
        ),
    ]
