# Generated by Django 4.2.6 on 2024-02-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_cargo_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='match',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', verbose_name='match'),
        ),
    ]
