# Generated by Django 4.2.6 on 2024-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_clientes_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y%m/', verbose_name='Foto'),
        ),
    ]
