# Generated by Django 4.2.6 on 2024-03-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clientes_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='foto',
        ),
        migrations.AddField(
            model_name='clientes',
            name='foto_Usuario',
            field=models.ImageField(blank=True, null=True, upload_to='Foto_usuario/%Y%m/', verbose_name='Foto Usuario'),
        ),
    ]
