# Generated by Django 4.2.6 on 2024-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_clientes_foto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto_Usuario',
            field=models.ImageField(blank=True, null=True, upload_to='imageUser/%Y%m/', verbose_name='Foto Usuario'),
        ),
    ]
